version: '3.4'

services:
  frontend:
    container_name: frontend_aboutsatoskit_1
    build: 
      context: ./client_aboutsatoskit
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks: 
      - backend

  backend:
    container_name: backend_aboutsatoskit_1
    build: 
      context: ./backend_aboutsatoskit
      dockerfile: Dockerfile
    environment: 
      DATABASE_URLL : postgres://postgres:postgres@database:5432/aboutsatoskit
    ports:
      - 5000:5000
    depends_on: 
      - database
    networks: 
      - backend

  database: 
    # image: postgres
    container_name: postgres_aboutsatoskit_1
    build: 
      context: ./backend_aboutsatoskit
      dockerfile: Dockerfile-db
    env_file: backend_aboutsatoskit/config.env 
    ports:
      - 5432:5432
    networks: 
      - backend
    volumes:
      - db:/var/lib/postgersql/data
  
networks: 
  backend:

volumes: 
  db: